name: lgmvip_task3
description:AR fillter Project



version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  arcore_flutter_plugin: ^0.0.11
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ar.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 
  uses-material-design: true

 
  assets:
    - assets/mask.png
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
