name: lgmvip_task1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_spinkit: ^5.1.0

  url_launcher: ^6.0.12




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



flutter:


  uses-material-design: true
  fonts:
    - family: SanFrancisco
      fonts:
        - asset: fonts/SanFrancisco-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf

  assets:
    - assets/Logo.png
    - assets/Logo2.png
